# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kickr (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kickr (iOS)

# Add the Firebase pod for Google Analytics
pod 'FirebaseAnalytics'

pod 'FirebaseAuth'
pod 'FirebaseFirestore'

end

target 'Kickr (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kickr (macOS)

end
